import express from "express"; import cors from "cors"; import bcrypt from "bcryptjs"; import jwt from "jsonwebtoken"; import multer from "multer"; import path from "node:path"; import fs from "node:fs"; import {db} from "./db.js";
const app=express(), SECRET=process.env.JWT_SECRET||"dev-secret-change-me"; app.use(cors()); app.use(express.json()); app.use("/uploads",express.static(path.resolve("uploads")));
const auth=(req:any,res:any,next:any)=>{const h=req.headers.authorization;if(!h?.startsWith("Bearer "))return res.status(401).json({message:"Du måste logga in."});try{req.user=jwt.verify(h.slice(7),SECRET);next()}catch{return res.status(401).json({message:"Ogiltig session."})}};
const admin=(req:any,res:any,next:any)=>req.user.roll==="admin"?next():res.status(403).json({message:"Endast administratör."});
app.post("/api/login",(req,res)=>{const u=db.prepare("SELECT * FROM users WHERE epost=?").get(req.body.epost) as any;if(!u||!bcrypt.compareSync(req.body.password,u.password_hash))return res.status(401).json({message:"Fel e-post eller lösenord."});const user={id:u.id,namn:u.namn,roll:u.roll};res.json({user,token:jwt.sign(user,SECRET,{expiresIn:"8h"})})});app.get("/api/me",auth,(req:any,res)=>res.json(req.user));
const cfg:any={fastigheter:["namn","adress","antal_lagenheter","status","anteckning"],hyresgaster:["namn","lagenhet","telefon","epost","fastighet_id"],felanmalningar:["rubrik","beskrivning","fastighet_id","hyresgast_id","prioritet","status","skapad"],arbetsorder:["titel","beskrivning","ansvarig","status","datum","felanmalan_id"]};
for(const [table,fields] of Object.entries(cfg) as any){app.get(`/api/${table}`,auth,(_q,r)=>r.json(db.prepare(`SELECT * FROM ${table} ORDER BY rowid DESC`).all()));app.get(`/api/${table}/:id`,auth,(q,r)=>{const x=db.prepare(`SELECT * FROM ${table} WHERE id=?`).get(q.params.id);x?r.json(x):r.status(404).json({message:"Hittades inte."})});app.post(`/api/${table}`,auth,(q,r)=>{const id=crypto.randomUUID(),vals=fields.map((f:string)=>q.body[f]??null);db.prepare(`INSERT INTO ${table}(id,${fields.join(",")}) VALUES(?${",?".repeat(fields.length)})`).run(id,...vals);r.status(201).json(db.prepare(`SELECT * FROM ${table} WHERE id=?`).get(id))});app.put(`/api/${table}/:id`,auth,(q,r)=>{const up=fields.filter((f:string)=>f in q.body);db.prepare(`UPDATE ${table} SET ${up.map((f:string)=>`${f}=?`).join(",")} WHERE id=?`).run(...up.map((f:string)=>q.body[f]),q.params.id);r.json(db.prepare(`SELECT * FROM ${table} WHERE id=?`).get(q.params.id))});app.delete(`/api/${table}/:id`,auth,admin,(q,r)=>{db.prepare(`DELETE FROM ${table} WHERE id=?`).run(q.params.id);r.status(204).end()})}
app.get("/api/fastigheter/:id/detaljer",auth,(q,r)=>{const fastighet=db.prepare("SELECT * FROM fastigheter WHERE id=?").get(q.params.id);if(!fastighet)return r.status(404).json({message:"Hittades inte."});r.json({fastighet,hyresgaster:db.prepare("SELECT * FROM hyresgaster WHERE fastighet_id=?").all(q.params.id),felanmalningar:db.prepare("SELECT * FROM felanmalningar WHERE fastighet_id=?").all(q.params.id)})});
app.get("/api/felanmalningar/:id/detaljer",auth,(q,r)=>{const felanmalan=db.prepare("SELECT f.*,fa.namn fastighet_namn,h.namn hyresgast_namn FROM felanmalningar f LEFT JOIN fastigheter fa ON fa.id=f.fastighet_id LEFT JOIN hyresgaster h ON h.id=f.hyresgast_id WHERE f.id=?").get(q.params.id);if(!felanmalan)return r.status(404).json({message:"Hittades inte."});r.json({felanmalan,arbetsorder:db.prepare("SELECT * FROM arbetsorder WHERE felanmalan_id=?").all(q.params.id),bilder:db.prepare("SELECT * FROM bilder WHERE felanmalan_id=? ORDER BY uppladdad DESC").all(q.params.id)})});
const upload=multer({storage:multer.diskStorage({destination:(_q,_f,cb)=>cb(null,path.resolve("uploads")),filename:(_q,f,cb)=>cb(null,`${Date.now()}-${crypto.randomUUID()}${path.extname(f.originalname)}`)}),limits:{fileSize:5*1024*1024}});
app.post("/api/felanmalningar/:id/bilder",auth,upload.single("bild"),(q:any,r)=>{if(!q.file)return r.status(400).json({message:"Ingen bild."});const id=crypto.randomUUID();db.prepare("INSERT INTO bilder VALUES(?,?,?,?,?)").run(id,q.params.id,q.file.filename,q.file.originalname,new Date().toISOString());r.status(201).json({id})});app.delete("/api/bilder/:id",auth,admin,(q,r)=>{const b=db.prepare("SELECT * FROM bilder WHERE id=?").get(q.params.id) as any;if(b&&fs.existsSync(path.resolve("uploads",b.filnamn)))fs.unlinkSync(path.resolve("uploads",b.filnamn));db.prepare("DELETE FROM bilder WHERE id=?").run(q.params.id);r.status(204).end()});
app.get("/api/dashboard",auth,(_q,r)=>{const one=(s:string)=>(db.prepare(s).get() as any).c;r.json({fastigheter:one("SELECT COUNT(*) c FROM fastigheter"),lagenheter:one("SELECT COALESCE(SUM(antal_lagenheter),0)c FROM fastigheter"),hyresgaster:one("SELECT COUNT(*)c FROM hyresgaster"),oppnaArenden:one("SELECT COUNT(*)c FROM felanmalningar WHERE status!='Klar'"),arbetsorder:one("SELECT COUNT(*)c FROM arbetsorder WHERE status!='Klar'")})});
app.listen(4000,()=>console.log("Fastighetsnavet v3 API på http://localhost:4000"));
